export enum MenuActions {
  styleColumn = 'styleColumn',
  newColumn = 'newColumn',
  delColumn = 'delColumn',
  editColumn = 'editColumn',
  showColumns = 'showColumns',
  freezeColumn = 'freezeColumn',
  filter = 'filter',
  multiSort = 'multiSort',
  newRow = 'newRow',
  newRowBelow = 'newRowBelow',
  newRowChild= 'newRowChild',
  delRow = 'delRow',
  editRow = 'editRow',
  multiSelectRow = 'multiSelectRow',
  copyRow = 'copyRow',
  cutRow = 'cutRow',
  pasteRow = 'pasteRow',
  pasteRowSibling = 'pasteRowSibling',
  pasteRowChild = 'pasteRowChild'
}
